import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import PageTransition from "@/components/PageTransition";
import StairTransaction from "@/components/StairTransaction";
import Header from "@/components/Header";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} antialiased bg-slate-950 text-white jetbrains-mono`}
      >
        <Header />
        <StairTransaction />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
